# Generated by Django 4.2.6 on 2023-11-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('bank_branch', models.CharField(max_length=20)),
                ('IFSC', models.CharField(default='', max_length=20)),
                ('picture', models.ImageField(default='', upload_to='seller/')),
                ('account_number', models.CharField(max_length=20)),
                ('loginid', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
